config/routes.rb
AguaClara::Application.routes.draw do
  
  devise_for :administradores, :skip => [:registrations]
    as :administrador do
      get 'administradores/edit' => 'devise/registrations#edit', :as => 'edit_administrador_registration'
      put 'administradores/:id' => 'devise/registrations#update', :as => 'administrador_registration'            
    end
    
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'usuarios/sign_out' => 'devise/sessions#destroy', as: :logout

  get "entidades_territoriales/:id/ciudades" => 'entidades_territoriales#ciudades'
  get "entidades_territoriales/:id/municipios" => 'entidades_territoriales#municipios'
  get "entidades_territoriales/:id/parroquias" => 'entidades_territoriales#parroquias'
  get "entidades_territoriales/:id/direcciones" => 'entidades_territoriales#direcciones'
  
  get "instituciones/:id/entes_ejecutores" => 'dependents_selects#entes_ejecutores'
  get "unidades/:id/instituciones" => 'dependents_selects#instituciones'
  get "fuentes_financiamiento/:id/fondos_financiamiento" => 'dependents_selects#fondos_financiamiento'
  get "tipos_obras/:id/sub_tipos_obras" => 'dependents_selects#sub_tipos_obras'

  get "estados/:id/municipios" => 'dependents_selects#municipios'
  get "municipios/:id/parroquias" => 'dependents_selects#parroquias'
  get "parroquias/:id/sectores" => 'dependents_selects#sectores'

  get "/contratos" => "contratos#list", as: :contratos
  get "/contratos/search" => "contratos#search", as: :search_contratos

  get "/desembolsos" => "desembolsos#list", as: :desembolsos
  get "/desembolsos/search" => "desembolsos#search", as: :search_desembolsos

  resources :proyectos do
    get 'search', on: :collection
    get 'pdf', on: :member
    resources :actividades do
      get 'search', on: :collection
    end
    resources :bitacoras, controller: 'bitacora'
    resources :contratos do      
    end
    resources :desembolsos do
      get 'search', on: :collection
    end    
  end

  get "/valuaciones" => "valuaciones#list", as: :list_valuaciones
  get "/valuaciones/search" => "valuaciones#search", as: :search_valuaciones
  scope path:"/contratos/:contrato_id" do
   resources :valuaciones 
  end

  namespace "reportes" do
    resources :cantidades_obras do
        collection do
         get 'report'
       end
    end
    resources :proyectos do
        collection do
         get 'report'
       end
    end
    resources :actividades do
        collection do
         get 'report'
       end
    end
    resources :desembolsos do
        collection do
         get 'report'
       end
    end
  end

  

  root 'welcome#index'

end

app/models/proyecto.rb
class Proyecto < ActiveRecord::Base
  include Estados 
  
  attr_accessor :comentarios
  validates :nombre,
    length: { maximum: 255 },
    presence: true
  validates :descripcion,
    length: { maximum: 255 },
    presence: true
  validates :punto_cuenta,
    length: { maximum: 20 },
    presence: true
  validates :lapso_ejecucion_en_meses,
    numericality: { only_integer: true, greater_than: 0, allow_blank: true },
    presence: true
  validates :habitantes_beneficiados,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true },
    presence: true
  validates :empleos_directos,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true },
    presence: true
  validates :empleos_indirectos,
    numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_blank: true },
    presence: true  
  validates :monto_solicitado,
    numericality: { greater_than: 0, allow_blank: true },
    presence: false
  validates :monto_aprobado,
    numericality: { greater_than: 0, allow_blank: true },
    presence: false
  validates :numero_proyecto,
    length: { maximum: 15 },
    presence: true
  validates_presence_of :fecha_inicial, :fecha_final,
    :unidad, :ente_ejecutor, :institucion, :estatus3i, :tipo_obra,
    :sub_tipo_obra, :punto_cuenta
  validates_presence_of :comentarios, :on => :update
  
  validate :fechas

  validates :proyectos_financiamientos, :presence => true
  validates :montos_proyectos, :presence => true

  belongs_to :unidad
  belongs_to :ente_ejecutor
  belongs_to :institucion
  belongs_to :estatus3i, class_name: "Estatus3i", foreign_key: "estatus_id"
  belongs_to :tipo_obra
  belongs_to :sub_tipo_obra
  
  has_many :contratos, dependent: :destroy, inverse_of: :proyecto
  has_many :contratistas, through: :contratos
  has_many :actividades
  has_many :sectores, through: :proyectos_ubicaciones 
  has_many :estados, through: :proyectos_ubicaciones
  has_many :municipios, through: :proyectos_ubicaciones
  has_many :parroquias, through: :proyectos_ubicaciones
  has_many :desembolsos
  has_many :desembolsos_fuentes, through: :desembolsos
  has_many :bitacoras
  has_many :proyectos_financiamientos, class_name: "ProyectoFinanciamiento", dependent: :destroy
  has_many :proyectos_ubicaciones, class_name: "ProyectoUbicacion", dependent: :destroy
  has_many :montos_proyectos, class_name: "MontoProyecto", dependent: :destroy
  
  has_many :monedas, through: :montos_proyectos
  has_many :valuaciones, through: :contratos

  accepts_nested_attributes_for :proyectos_financiamientos, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :proyectos_ubicaciones, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :montos_proyectos, reject_if: :all_blank, allow_destroy: true
  
  scope :ente_ejecutor, ->(ente_ejecutor) {joins(:ente_ejecutor).where("entes_ejecutores.id = ?",ente_ejecutor)}
  scope :fuente_financiamiento, ->(fuente_financiamiento) {joins(:proyectos_financiamientos).where("proyectos_financiamientos.fuente_financiamiento_id = ?",fuente_financiamiento)}
  scope :fondo_financiamiento, ->(fondo_financiamiento) {joins(:proyectos_financiamientos).where("proyectos_financiamientos.fondo_financiamiento_id = ?",fondo_financiamiento)}
  scope :por_estado, ->(estado_id) {joins(:proyectos_ubicaciones).where("proyectos_ubicaciones.estado_id = ?",estado_id)}
  scope :por_municipio, ->(municipio_id) {joins(:proyectos_ubicaciones).where("proyectos_ubicaciones.municipio_id = ?",municipio_id)}
  scope :por_parroquia, ->(parroquia_id) {joins(:proyectos_ubicaciones).where("proyectos_ubicaciones.parroquia_id = ?",parroquia_id)}
  scope :por_sector, ->(sector_id) {joins(:proyectos_ubicaciones).where("proyectos_ubicaciones.sector_id = ?",sector_id)}
  scope :tipo_obra, ->(tipo_obra) {joins(:tipo_obra).where(s"tipos_obras.id = ?",tipo_obra)}
  scope :sub_tipo_obra, ->(sub_tipo_obra) {joins(:sub_tipo_obra).where("sub_tipos_obras.id = ?",sub_tipo_obra)}
  scope :estatus_3i, ->(estatus_3i) {where("estatus_id = ?",estatus_3i)}
  scope :punto_cuenta, ->(punto_cuenta) {where("punto_cuenta = ?",punto_cuenta)}
  scope :estatus_transferencia, ->(estatus_transferencia) {joins(:desembolso).where("desembolsos.estatus_id = ?",estatus_transferencia)}
  scope :por_proyecto, ->(proyecto) {where("lower(nombre) like ?","%#{proyecto.downcase}%")}
  scope :numero_proyecto, ->(numero_proyecto) {where("lower(numero_proyecto) like ?","%#{numero_proyecto.downcase}%")}
  scope :unidad, ->(unidad) {joins(:unidad).where("unidades.id = ?",unidad)}
  scope :impacto, ->(impacto) {where("impacto = ?",impacto)}
  scope :posee_recurso, ->(posee_recurso) {where("posee_recursos = ?",posee_recurso)}
  scope :fecha_inicial, ->(fecha_inicial) {where("fecha_inicial >= ?",fecha_inicial)}
  scope :fecha_final, ->(fecha_final) {where("fecha_final <= ?",fecha_final)}
  scope :institucion, ->(institucion) {joins(:institucion).where("instituciones.id = ?",institucion)}  
  scope :iniciadas, ->{where(estatus_dinamico: "inicio")}
  scope :ejecutandose, ->{where(estatus_dinamico: "ejecucion")}
  scope :inauguradas, ->{where(estatus_dinamico: "inaugurada")}
  scope :listado_desembolsos, ->(sub_tipo_obra) {joins(:sub_tipo_obra).where("sub_tipos_obras.id = ?",sub_tipo_obra)}




  def self.search_by_query(query)
    result = self.all
    if !query["ente_ejecutor"].nil? && !query["ente_ejecutor"].empty?
      result = result.ente_ejecutor(query["ente_ejecutor"])
    end
    if !query["fuente_financiamiento"].nil? && !query["fuente_financiamiento"].to_s.empty?
      result = result.fuente_financiamiento(query["fuente_financiamiento"])
    end
    if !query["fondo_financiamiento"].nil? && !query["fondo_financiamiento"].to_s.empty?
      result = result.fondo_financiamiento(query["fondo_financiamiento"])
    end
    if !query["tipo_obra"].nil? && !query["tipo_obra"].to_s.empty?
      result = result.tipo_obra(query["tipo_obra"])
    end
    if !query["sub_tipo_obra"].nil? && !query["sub_tipo_obra"].to_s.empty?
      result = result.sub_tipo_obra(query["sub_tipo_obra"])
    end
    if !query["estatus_3i"].nil? && !query["estatus_3i"].to_s.empty?
      result = result.estatus_3i(query["estatus_3i"])
    end
    if !query["estatus_transferencia"].nil? && !query["estatus_transferencia"].to_s.empty?
      result = result.estatus_transferencia(query["estatus_transferencia"])
    end
    if !query["proyecto"].nil? && !query["proyecto"].to_s.empty?
      result = result.por_proyecto(query["proyecto"])
    end
    if !query["nombre"].nil? && !query["nombre"].to_s.empty?
      result = result.por_proyecto(query["nombre"])
    end
    if !query["numero_proyecto"].nil? && !query["numero_proyecto"].to_s.empty?
      result = result.numero_proyecto(query["numero_proyecto"])
    end
    if !query["punto_cuenta"].nil? && !query["punto_cuenta"].to_s.empty?
      result = result.punto_cuenta(query["punto_cuenta"])
    end
    if !query["unidad"].nil? && !query["unidad"].to_s.empty?
      result = result.unidad(query["unidad"])
    end
    if !query["impacto"].nil? && !query["impacto"].to_s.empty?
      result = result.impacto(query["impacto"])
    end
    if !query["posee_recurso"].nil? && !query["posee_recurso"].to_s.empty?
      result = result.posee_recurso(query["posee_recurso"])
    end
    if !query["institucion"].nil? && !query["institucion"].to_s.empty?
      result = result.institucion(query["institucion"])
    end
    if !query["fecha_inicial"].nil? && !query["fecha_inicial"].to_s.empty?
      result = result.fecha_inicial(query["fecha_inicial"])
    end
    if !query["fecha_final"].nil? && !query["fecha_final"].to_s.empty?
      result = result.fecha_final(query["fecha_final"])
    end
    if !query["estado_id"].nil? && !query["estado_id"].to_s.empty?
      result = result.por_estado(query["estado_id"])
    end
    if !query["municipio_id"].nil? && !query["municipio_id"].to_s.empty?
      result = result.por_municipio(query["municipio_id"])
    end
    if !query["parroquia_id"].nil? && !query["parroquia_id"].to_s.empty?
      result = result.por_parroquia(query["parroquia_id"])
    end
    if !query["sector_id"].nil? && !query["sector_id"].to_s.empty?
      result = result.por_sector(query["sector_id"])
    end
    result
  end
 
  def porcentaje_avance_fisico
    ejecucion_fisica
  end
  
  def porcentaje_avance_financiero
    ejecucion_financiera
  end

  rails_admin do
    list do
      field :nombre
      field :descripcion
      field :fecha_inicial
      field :fecha_final
    end
  end
 

  def ejecucion_fisica
    actividades.inject(0){|sum,e| sum += e.porcentaje_global}.round(2)
  end

  def ejecucion_financiera
    ta = total_aprobado
    tv = total_valuaciones
    if ta > 0.0 
      ((tv * 100) / ta).round(2)
    else
      0.0
    end
  end

  def total_aprobado
    total = 0
    montos_proyectos.includes(:moneda).each do |m|
      total += m.aprobado * m.moneda.valor if m.moneda.aumenta?
      total += m.aprobado / m.moneda.valor unless m.moneda.aumenta?
    end
    total.round(2)
  end

  def total_valuaciones
    total = 0
    MontoValuacion.por_proyecto(id).includes(:moneda).each do |m|
      total += m.monto * m.moneda.valor if m.moneda.aumenta?
      total += m.monto / m.moneda.valor unless m.moneda.aumenta?
    end
    total.round(2)
  end

  def pesos
    actividades.inject(0){|sum,e| sum += e.peso}
  end

  def montos_solicitados
    return montos_proyectos.map{|d| "#{d.solicitado} #{d.moneda.simbolo}"}.join(", ") unless montos_proyectos.nil?
  end

  def montos_aprobados
    return montos_proyectos.map{|d| "#{d.aprobado} #{d.moneda.simbolo}"}.join(", ") unless montos_proyectos.nil?
  end

  def self.datos_grafico_ejecucion_financiera
    datos = []
    Moneda.all.each do |m|
      datos.push({name: m.simbolo, data: [
          m.montos_proyectos.sum(:solicitado),
          m.montos_proyectos.sum(:aprobado),
          m.desembolsos_fuentes.sum(:monto),

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :configurar_listas, only: [:new, :create, :edit, :update] 
  before_action :buscar_proyecto, only: [:edit, :update, :destroy, :show, :pdf]
  before_filter :buscar_fuentes_financiamientos
  before_filter :buscar_fondos_financiamientos


  # GET /proyectos
  def index
    @proyectos = Proyecto.all
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end



  def pdf
    render :pdf => 'proyecto', :layout => 'pdf.html'    
  end

  # POST /proyectos
  def create
    @proyecto = Proyecto.new proyecto_params
    if @proyecto.save
      redirect_to proyectos_url, notice: 'El proyecto se ha creado satisfactoriamente.'
    else      
      render action: 'new'
    end
  end

  # GET /proyectos/:id/edit
  def edit
  end

  # PUT /proyectos/:id
  # PATCH /proyectos/:id
  def update
    if @proyecto.update proyecto_params
      bitacora = Bitacora.new(:titulo =>"Actualización del proyecto #{@proyecto.nombre}", :observaciones => @proyecto.comentarios, :proyecto_id => @proyecto.id)
      bitacora.usuario = current_user
      bitacora.save
      logger.info bitacora.inspect
      redirect_to proyectos_url, notice: 'El proyecto ha sido actualizado satisfactoriamente.'
    else
      render action: 'edit'
    end
  end

  # DELETE /proyectos/:id
  def destroy
    if @proyecto.destroy
      redirect_to proyectos_url, notice: 'El proyecto ha sido actualizado satisfactoriamente.'
    else
      redirect_to proyectos_url, notice: 'El proyecto ha sido actualizado satisfactoriamente.'
    end      
  end

  # GET /proyectos/search
  def search
    @proyectos = Proyecto.search_by_query(params[:search])
    render :index
  end

private

  # Busca el proyecto especificado por +params[:id]+
  # Llamado como before_action
  def buscar_proyecto
    @proyecto = Proyecto.find params[:id]
  end

  # Configura las variables de instancias para cargar
  # los diferentes +selects+ del formulario
  def configurar_listas
    @unidades = Unidad.order(:nombre)
    @estatus3i = Estatus3i.all
    @tipos_obras = TipoObra.order(:nombre)
    @estados = EntidadTerritorial::Estado.order(:nombre)
    @municipios = EntidadTerritorial::Municipio.order(:nombre)
    @parroquias = EntidadTerritorial::Parroquia.order(:nombre)
    @sectores = Sector.order(:nombre)
  end
  def buscar_fondos_financiamientos
    @fondos_financiamientos = FondoFinanciamiento.all
  end
  def buscar_fuentes_financiamientos
    @fuentes_financiamientos = FuenteFinanciamiento.all
  end

  def proyecto_params
    params[:proyecto].permit(:nombre,:descripcion,:fecha_inicial, :fecha_final, :lapso_ejecucion_en_meses, :monto_solicitado, :monto_aprobado,
      :unidad_id, :ente_ejecutor_id, :institucion_id, :estatus_id, :impacto, :punto_cuenta, :tipo_obra_id, :sub_tipo_obra_id, :numero_proyecto, :comentarios, :posee_recursos, :habitantes_beneficiados, :empleos_directos, :empleos_indirectos, 
      proyectos_financiamientos_attributes: [:id, :fuente_financiamiento_id, :fondo_financiamiento_id, :_destroy], 
      proyectos_ubicaciones_attributes: [:id, :proyecto_id, :estado_id, :municipio_id, :parroquia_id, :sector_id, :_destroy],
      montos_proyectos_attributes: [:id, :moneda_id, :solicitado, :aprobado, :_destroy])
  end
end

app/controllers/reportes/proyectos_controller.rb
class Reportes::ProyectosController < ApplicationController
	authorize_resource class: Reportes::ProyectosController
	#Página principal del reporte. Alli es donde se visualizan los campos que filtran el reporte
	def index
	end

	def report
		@proyectos = Proyecto.search_by_query(params[:search])
		render "report", :formats => [:pdf]
	end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/helpers/reportes/proyectos_helper.rb
module Reportes::ProyectosHelper
end

app/views/proyectos/_filtro.html.haml
= simple_form_for :search, {url: search_proyectos_path, method: :get} do |f|
  %div.row-fluid
    .span7.first
      = f.input :nombre, label: false, placeholder: 'Nombre', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
    .span3
      = f.input :numero_proyecto, label: false, placeholder: 'Número de Proyecto', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
  %div.row-fluid
    .span12
      = f.select :fuente_financiamiento, FuenteFinanciamiento.all.map{ |r| [r.nombre, r.id] }, :label => false, prompt: "Fuente de inanciamiento"
      = select_tag 'search[fondo_financiamiento]', options_from_collection_for_select([], "id", "nombre"), :label => false, prompt: "Fondo de Financiamiento",
        :"data-option-dependent" => true, 
        :"data-option-observed" => "search_fuente_financiamiento", 
        :"data-option-url" => "/fuentes_financiamiento/:search_fuente_financiamiento:/fondos_financiamiento.json", 
        :"data-option-key-method" => :id, 
        :"data-option-value-method" => :nombre  
      = f.select :tipo_obra, TipoObra.all.map{ |r| [r.nombre, r.id] }, :label => false, prompt: "Tipo de Obra"
      = select_tag 'search[sub_tipo_obra]', options_from_collection_for_select([], "id", "nombre"), :label => false, prompt: "Sub Tipo de Obra",
        :"data-option-dependent" => true, 
        :"data-option-observed" => "search_tipo_obra", 
        :"data-option-url" => "/tipos_obras/:search_tipo_obra:/sub_tipos_obras.json", 
        :"data-option-key-method" => :id, 
        :"data-option-value-method" => :nombre 
  %div.row-fluid
    .span12
      = render 'reportes/proyectos/entidad_territorial_fields', :f => f
  %div.row-fluid
    .span12
      = f.select :unidad, Unidad.all.map{ |r| [r.nombre, r.id] }, :label => false, prompt: "Unidad"
      = select_tag 'search[institucion]', options_from_collection_for_select([], "id", "nombre"), :label => false, prompt: "Institución",
        :"data-option-dependent" => true, 
        :"data-option-observed" => "search_unidad", 
        :"data-option-url" => "/unidades/:search_unidad:/instituciones.json", 
        :"data-option-key-method" => :id, 
        :"data-option-value-method" => :nombre  
      = select_tag 'search[ente_ejecutor]', options_from_collection_for_select([], "id", "nombre"), :label => false, prompt: "Ente Ejecutor",
        :"data-option-dependent" => true, 
        :"data-option-observed" => "search_institucion", 
        :"data-option-url" => "/instituciones/:search_institucion:/entes_ejecutores.json", 
        :"data-option-key-method" => :id, 
        :"data-option-value-method" => :nombre  
    %div.row-fluid
      .span12.first
      = button_tag(class: 'btn btn-icon btn-primary glyphicons search') do
        - content_tag(:i, '') + "Buscar"
      = link_to(proyectos_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
        - content_tag(:i, '') + "Cancelar"  

app/views/proyectos/_listado.html.haml
%table.table.table-condensed.table-striped
  %thead
    %tr
      %th="No. de Proyecto"  
      %th="Actividad Solicitada / Nombre Proyecto"  
      %th="Monto Solicitado"
      %th="Monto Aprobado"
      %th="Fecha Inicial"
      %th="Fecha Final"
      %th="Estatus"
      %th="Estatus 3i"
      %th="Ejecución Física"
      %th="Ejecución Financiera"
      %th=""
  %tbody
    - if params[:page].nil? || params[:page] == "0" || params[:page] == "1" 
      - contador = 0 
    - else 
      - page = params[:page].to_i - 1 
      - contador = page * 15 
    - @proyectos.each do |p|
      %tr
        %td 
          =contador += 1
          =link_to(image_tag("pdf-icon.png"), pdf_proyecto_path(p, format: :pdf))
        %td= link_to(p.nombre, proyecto_path(p))
        %td= p.montos_solicitados
        %td= p.montos_aprobados
        %td= p.fecha_inicial
        %td= p.fecha_final
        %td
          %span.label.label-primary= p.estatus_dinamico
        %td= p.estatus3i.nombre
        %td
          %a.widget-stats-easy-pie{:href => "#"}
            .easy-pie.easyPieChart{"data-percent" => "#{p.ejecucion_fisica}", :style => "width: 50px; height: 50px; line-height: 50px;"}
              %span.value= "#{p.ejecucion_fisica}%"
              %canvas{:height => "50", :width => "50"}
            .clearfix
        %td
          %a.widget-stats-easy-pie{:href => "#"}
            .easy-pie.easyPieChart{"data-percent" => "#{p.ejecucion_financiera}", :style => "width: 50px; height: 50px; line-height: 50px;"}
              %span.value= "#{p.ejecucion_financiera}%"
              %canvas{:height => "50", :width => "50"}
            .clearfix
        %td{style: 'width: 60px'}
          = link_to(edit_proyecto_path(p), class: 'pjax', title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }
          = link_to(proyecto_path(p), method: :delete, class: 'pjax', title: 'Eliminar', data: {confirm: '¿Desea eliminar el proyecto?'}){ content_tag(:i, '', class:"icon-remove") }
          = link_to(proyecto_actividades_path(p), class: 'pjax', title: 'Actividades'){ content_tag(:i, '', class:"icon-tasks") }
          = link_to(proyecto_contratos_path(p), class: 'pjax', title: 'Contratos'){ content_tag(:i, '', class:"icon-book") }  
          = link_to(proyecto_bitacoras_path(p), class: 'pjax', title: 'Bitacoras'){ content_tag(:i, '', class:"icon-list-alt") }
          = link_to(proyecto_desembolsos_path(p), class: 'pjax', title: 'Desembolsos'){ content_tag(:i, '', class:"icon-tags") }

app/views/proyectos/_monto_proyecto.html.haml
#montos_proyectos
  = error_message("Debe agregar un monto al proyecto") unless @proyecto.errors.messages[:montos_proyectos].blank?
  = f.simple_fields_for :montos_proyectos do |o|
    = render 'monto_proyecto_fields', :f => o 
  .links
    = link_to_add_association(f, :montos_proyectos,  { class: 'btn btn-icon glyphicons circle_plus btn-success' }){ content_tag('i') + ' Agregar Montos Aprobados/Solicitados del Proyecto' }

app/views/proyectos/edit.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(proyectos_path, class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_path, class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
        %li.icon.edit_member_link.active
          = link_to(edit_proyecto_path(@proyecto), class: 'pjax'){ content_tag(:i, '', class:"icon-pencil") + content_tag(:span, ' Editar') }
        %li.icon.delete_member_link 
          = link_to(proyecto_path(@proyecto), method: :delete, class: 'pjax'){ content_tag(:i, '', class:"icon-remove") + content_tag(:span, ' Eliminar') }
    %div.widget-body
      %div.tab-content

        = simple_form_for @proyecto do |f| 
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span11
              %div.row-fluid
                = render 'form_fields', :f => f
              %div.span10
                %div.row-fluid
                  = f.input :comentarios, as: :text, input_html: {maxlength: 255, row:4, class: 'span12'}
          %br
          = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
            - content_tag(:i, '') + "Guardar"
          = link_to(proyectos_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Cancelar"
      

app/views/proyectos/index.html.haml
%ul.breadcrumb
  %li.active
    %a="Proyectos"

%h3="Lista de Proyectos"

%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link.active
          = link_to(proyectos_path, class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_path, class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
        %li.icon.export_collection_link 
          = link_to('admin/proyecto/export'){ content_tag(:i, '', class:"icon-share") + content_tag(:span, ' Exportar') }          
    %div.widget-body
      %div.tab-content
        %div.list
          %div.well
            .row-fluid.no-margin-bottom
              = render 'filtro'
          = flash_messages
          = render 'listado'                  
      .clearfix.total-count= pluralize(@proyectos.size, 'proyecto')


    

app/views/proyectos/show.html.haml
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(proyectos_path, class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_path, class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
        %li.icon.edit_member_link
          = link_to(edit_proyecto_path(@proyecto), class: 'pjax'){ content_tag(:i, '', class:"icon-pencil") + content_tag(:span, ' Editar') }
        %li.icon.delete_member_link 
          = link_to(proyecto_path(@proyecto), method: :delete, class: 'pjax', confirm: '¿Desea eliminar el proyecto?'){ content_tag(:i, '', class:"icon-remove") + content_tag(:span, ' Eliminar') }
    %div.widget-body
      %div.tab-content
        = render 'proyecto'
      