config/routes.rb
AguaClara::Application.routes.draw do
  
  devise_for :administradores, :skip => [:registrations]
    as :administrador do
      get 'administradores/edit' => 'devise/registrations#edit', :as => 'edit_administrador_registration'
      put 'administradores/:id' => 'devise/registrations#update', :as => 'administrador_registration'            
    end
    
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'usuarios/sign_out' => 'devise/sessions#destroy', as: :logout

  get "entidades_territoriales/:id/ciudades" => 'entidades_territoriales#ciudades'
  get "entidades_territoriales/:id/municipios" => 'entidades_territoriales#municipios'
  get "entidades_territoriales/:id/parroquias" => 'entidades_territoriales#parroquias'
  get "entidades_territoriales/:id/direcciones" => 'entidades_territoriales#direcciones'
  
  get "instituciones/:id/entes_ejecutores" => 'dependents_selects#entes_ejecutores'
  get "unidades/:id/instituciones" => 'dependents_selects#instituciones'
  get "fuentes_financiamiento/:id/fondos_financiamiento" => 'dependents_selects#fondos_financiamiento'
  get "tipos_obras/:id/sub_tipos_obras" => 'dependents_selects#sub_tipos_obras'

  get "estados/:id/municipios" => 'dependents_selects#municipios'
  get "municipios/:id/parroquias" => 'dependents_selects#parroquias'
  get "parroquias/:id/sectores" => 'dependents_selects#sectores'

  get "/contratos" => "contratos#list", as: :contratos
  get "/contratos/search" => "contratos#search", as: :search_contratos

  get "/desembolsos" => "desembolsos#list", as: :desembolsos
  get "/desembolsos/search" => "desembolsos#search", as: :search_desembolsos

  resources :proyectos do
    get 'search', on: :collection
    get 'pdf', on: :member
    resources :actividades do
      get 'search', on: :collection
    end
    resources :bitacoras, controller: 'bitacora'
    resources :contratos do      
    end
    resources :desembolsos do
      get 'search', on: :collection
    end    
  end

  get "/valuaciones" => "valuaciones#list", as: :list_valuaciones
  get "/valuaciones/search" => "valuaciones#search", as: :search_valuaciones
  scope path:"/contratos/:contrato_id" do
   resources :valuaciones 
  end

  namespace "reportes" do
    resources :cantidades_obras do
        collection do
         get 'report'
       end
    end
    resources :proyectos do
        collection do
         get 'report'
       end
    end
    resources :actividades do
        collection do
         get 'report'
       end
    end
    resources :desembolsos do
        collection do
         get 'report'
       end
    end
  end

  

  root 'welcome#index'

end

app/models/bitacora.rb
class Bitacora < ActiveRecord::Base
  
  has_attached_file :file
  #validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  belongs_to :proyecto
  belongs_to :usuario, class_name: 'Administrador'

  validates :titulo, :proyecto, :usuario, presence: true
  validates_attachment :file, :size => { :in => 0..1000.kilobytes }
end

app/controllers/bitacora_controller.rb
class BitacoraController < ApplicationController
  before_action :buscar_proyecto
  before_action :buscar_bitacora, only: [:edit, :update, :destroy]


  # GET /bitacoras
  def index
    @bitacoras = @proyecto.bitacoras
  end

  # GET /bitacoras/new
  def new
    @bitacora = @proyecto.bitacoras.new 
  end

  # POST /bitacoras
  def create
    @bitacora = @proyecto.bitacoras.new bitacora_params
    @bitacora.file = params[:bitacora][:file]
    @bitacora.usuario = current_user
    if @bitacora.save
      redirect_to proyecto_bitacoras_url, notice: 'La nota se ha creado satisfactoriamente.'
    else
      render action: 'new'
    end
  end

  # GET /bitacoras/:id/edit
  def edit
  end

  # PUT /bitacoras/:id
  # PATCH /bitacoras/:id
  def update
    @bitacora.file = params[:bitacora][:file]
    if @bitacora.update bitacora_params
      redirect_to proyecto_bitacoras_url, notice: 'La nota ha sido actualizado satisfactoriamente.'
    else
      render action: 'edit'
    end
  end

  # DELETE /bitacoras/:id
  def destroy
    if @bitacora.destroy
      redirect_to proyecto_bitacoras_url, notice: "La nota '#{@bitacora.titulo}' ha sido eliminada satisfactoriamente."
    else      
      redirect_to proyecto_bitacoras_url, notice: 'Ha ocurrido un error al eliminar la nota.<br/>'+@bitacora.errors.full_messages
    end      
  end 

private

  # Busca el proyecto especificado por +params[:proyecto_id]+
  # Llamado como before_action
  def buscar_proyecto
    @proyecto = Proyecto.find params[:proyecto_id]
  end  

  # Busca la bitácora especificada por +params[:id]+
  # Llamado como before_action
  def buscar_bitacora
    @bitacora = @proyecto.bitacoras.find(params[:id])
  end

  def bitacora_params
    params[:bitacora].permit(:titulo,:observaciones)
  end

end

app/helpers/bitacora_helper.rb
module BitacoraHelper
end

app/views/bitacora/_filtro.html.haml
= simple_form_for :valuacion, {url: search_valuaciones_path, method: :get} do |f|
  .row-fluid
    .span3.first            
      = f.input :numero_valuacion, label: false, placeholder: 'Número valuación', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
    .span3
      = f.input :numero_contrato, label: false, placeholder: 'Número contrato', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
    .span6
      = f.input :ingeniero_inspector, label: false, placeholder: 'Ingeniero inspector', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
  .row-fluid
    .span6.first            
      = f.input :nombre_proyecto, label: false, placeholder: 'Proyecto', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}  
    .span3            
      = f.input :desde, label: false, placeholder: 'Desde', :as => :date_picker, input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}  
    .span3          
      = f.input :hasta, label: false, placeholder: 'Hasta',:as => :date_picker, input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}        
  .row-fluid
    .span12.first
      = button_tag(class: 'btn btn-icon btn-primary glyphicons search') do
        - content_tag(:i, '') + "Buscar"
      = link_to(list_valuaciones_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
        - content_tag(:i, '') + "Cancelar"  

app/views/bitacora/_form_fields.html.haml
.span10
  .row-fluid
    = f.input :titulo, input_html: {class: 'span12'}
    = f.input :observaciones, as: :text, input_html: {class: 'span12', rows: '10'}
    
  .row-fluid
    .span6
      = f.input :file, as: :file  
    .span6{style: 'text-align:center'}
      - unless @bitacora.file.blank?
        .box-generic{style: 'min-height:100px'}
          - if @bitacora.file.content_type.match(/image/)
            = image_tag @bitacora.file.url, size: '100x100'    
          - else
            = link_to(@bitacora.file_file_name,@bitacora.file.url)
          .ribbon-wrapper
            .ribbon.primary= "Archivo"

app/views/bitacora/_listado.html.haml
%table.table.table-condensed.table-striped
  %thead
    %tr
      %th="Fecha"
      %th="Título"        
      %th="Observaciones"            
      %th="Usuario"
      %th="Adjunto"
      %th=""
  %tbody
    - @bitacoras.each do |p|
      %tr
        %td= l p.created_at, format: :only_date
        %td= p.titulo        
        %td= p.observaciones && p.observaciones.length > 100 ? "#{p.observaciones[0..100]}..." : p.observaciones       
        %td= p.usuario.nombre
        %td.adjunto= link_to(p.file.url, class: 'glyphicons paperclip', title: 'Descargar') { content_tag :i } unless p.file.blank?
        %td
          = link_to(edit_proyecto_bitacora_path(@proyecto, p), class: 'pjax', title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }
          = link_to(proyecto_bitacora_path(@proyecto, p), method: :delete, class: 'pjax', title: 'Eliminar',data: {confirm: '¿Desea eliminar la nota?'}){ content_tag(:i, '', class:"icon-remove") }

app/views/bitacora/edit.html.haml
%div.innerLR
  %h3 Editando Bitácora
  = render 'shared/descripcion_proyecto'
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(proyecto_bitacoras_path(@proyecto), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_bitacora_path(@proyecto), class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
        %li.icon.edit_member_link.active
          = link_to(edit_proyecto_bitacora_path(@proyecto,@bitacora), class: 'pjax'){ content_tag(:i, '', class:"icon-pencil") + content_tag(:span, ' Editar') }
        %li.icon.delete_member_link 
          = link_to(proyecto_bitacora_path(@proyecto,@bitacora), method: :delete, class: 'pjax', confirm: '¿Desea eliminar la nota?'){ content_tag(:i, '', class:"icon-remove") + content_tag(:span, ' Eliminar') }
    %div.widget-body
      %div.tab-content

        = simple_form_for :bitacora, {url:proyecto_bitacora_path(@proyecto, @bitacora), method: :put} do |f| 
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span11
              %div.row-fluid
                = render 'form_fields', :f => f
          %br
          = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
            - content_tag(:i, '') + "Guardar"
          = link_to(proyecto_bitacoras_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Cancelar"
      

app/views/bitacora/index.html.haml
%ul.breadcrumb
  %li.false
    = link_to "Panel de control", root_path, class: 'pjax'
    %span.divider="/"
  %li.active
    %a="Bitacora"

%h3="Lista de Notas"

= render 'shared/descripcion_proyecto'
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link.active
          = link_to(proyecto_bitacoras_path(@proyecto), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_bitacora_path(@proyecto), class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
    %div.widget-body
      %div.tab-content
        %div.list      
          = flash_messages
          = render 'listado'                  
      .clearfix.total-count= pluralize(@bitacoras.size, 'nota')


    

app/views/bitacora/new.html.haml
%div.innerLR
  %h3 Agregar Nueva Bitácora
  = render 'shared/descripcion_proyecto'
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link
          = link_to(proyecto_bitacoras_path(@proyecto), class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link.active
          = link_to(new_proyecto_bitacora_path, class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
    %div.widget-body
      %div.tab-content

        = simple_form_for @bitacora, url: proyecto_bitacoras_path, :html => { :multipart => true } do |f| 
          = f.error_notification 
          = flash_messages
       
          %div.row-fluid
            %div.span11
              %div.row-fluid
                = render 'form_fields', :f => f
          %br
          = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
            - content_tag(:i, '') + "Guardar"
          = link_to(proyecto_bitacoras_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
            - content_tag(:i, '') + "Cancelar"

      