config/routes.rb
AguaClara::Application.routes.draw do
  
  devise_for :administradores, :skip => [:registrations]
    as :administrador do
      get 'administradores/edit' => 'devise/registrations#edit', :as => 'edit_administrador_registration'
      put 'administradores/:id' => 'devise/registrations#update', :as => 'administrador_registration'            
    end
    
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  
  get 'usuarios/sign_out' => 'devise/sessions#destroy', as: :logout

  get "entidades_territoriales/:id/ciudades" => 'entidades_territoriales#ciudades'
  get "entidades_territoriales/:id/municipios" => 'entidades_territoriales#municipios'
  get "entidades_territoriales/:id/parroquias" => 'entidades_territoriales#parroquias'
  get "entidades_territoriales/:id/direcciones" => 'entidades_territoriales#direcciones'
  
  get "instituciones/:id/entes_ejecutores" => 'dependents_selects#entes_ejecutores'
  get "unidades/:id/instituciones" => 'dependents_selects#instituciones'
  get "fuentes_financiamiento/:id/fondos_financiamiento" => 'dependents_selects#fondos_financiamiento'
  get "tipos_obras/:id/sub_tipos_obras" => 'dependents_selects#sub_tipos_obras'

  get "estados/:id/municipios" => 'dependents_selects#municipios'
  get "municipios/:id/parroquias" => 'dependents_selects#parroquias'
  get "parroquias/:id/sectores" => 'dependents_selects#sectores'

  get "/contratos" => "contratos#list", as: :contratos
  get "/contratos/search" => "contratos#search", as: :search_contratos

  get "/desembolsos" => "desembolsos#list", as: :desembolsos
  get "/desembolsos/search" => "desembolsos#search", as: :search_desembolsos

  resources :proyectos do
    get 'search', on: :collection
    get 'pdf', on: :member
    resources :actividades do
      get 'search', on: :collection
    end
    resources :bitacoras, controller: 'bitacora'
    resources :contratos do      
    end
    resources :desembolsos do
      get 'search', on: :collection
    end    
  end

  get "/valuaciones" => "valuaciones#list", as: :list_valuaciones
  get "/valuaciones/search" => "valuaciones#search", as: :search_valuaciones
  scope path:"/contratos/:contrato_id" do
   resources :valuaciones 
  end

  namespace "reportes" do
    resources :cantidades_obras do
        collection do
         get 'report'
       end
    end
    resources :proyectos do
        collection do
         get 'report'
       end
    end
    resources :actividades do
        collection do
         get 'report'
       end
    end
    resources :desembolsos do
        collection do
         get 'report'
       end
    end
  end

  

  root 'welcome#index'

end

app/models/desembolso.rb
class Desembolso < ActiveRecord::Base
  validates :fecha,
    presence: true
  validates :observacion,
    length: { maximum: 255 }
  validates :monto,
    numericality: { greater_than: 0, allow_blank: true },
    presence: false

  validates :estatus_transferencia, :valuacion,
  presence: true


  belongs_to :proyecto
  belongs_to :estatus_transferencia, class_name: "EstatusTransferencia", foreign_key: "estatus_id"
  
  has_many :desembolsos_fuentes, class_name: "DesembolsoFuente", dependent: :destroy
  #has_many :fuentes_financiamiento, through: :desembolsos_fuentes

  accepts_nested_attributes_for :desembolsos_fuentes, reject_if: :all_blank, allow_destroy: true

   scope :por_proyecto, ->(proyecto_id) {where("proyectos.id = ?",proyecto_id).joins(contrato: :proyecto)}

  def montos
    return desembolsos_fuentes.map{|d| "#{d.monto} #{d.moneda.simbolo}"}.join(", ") unless desembolsos_fuentes.nil?
  end

  def self.datos_grafico_desembolsos
    datos = []
    EstatusTransferencia.all.each do |e|
      datos.push([e.nombre, e.desembolsos.count])
    end
    datos
  end    
end

app/controllers/desembolsos_controller.rb
class DesembolsosController < ApplicationController
	before_filter :buscar_proyecto, :except => [:list]
	before_filter :buscar_proyectos_financiamientos
	before_filter :buscar_estatus_transferencia
	before_filter :buscar_fondos_financiamientos
	before_filter :buscar_desembolso, :except => [:index, :search, :new, :create, :list]

	def index
		@desembolsos = @proyecto.desembolsos.page params[:page]
	end
	def new
		@desembolso = Desembolso.new 
	end
	def create
		@desembolso = Desembolso.new(desembolso_params)
		@desembolso.proyecto = @proyecto
		if @desembolso.save
			flash[:notice] = "El Desembolso ha sido creada satisfactoriamente."
			redirect_to proyecto_desembolsos_path(@proyecto)
		else
			flash.now[:error] = "Ocurrieron errores al guardar."
      		render action: "new"
		end
	end
	def list
		@proyectos = Proyecto.order(:nombre)
		@desembolsos = Desembolso.order(:proyecto_id)
	end
	def search
		@desembolsos = Desembolso.order(:proyecto_id)
		@desembolsos = @desembolsos.where("estatus_id = ?", params[:desembolso][:estatus_transferencia_id]) unless params[:desembolso][:estatus_transferencia_id].blank?
		@desembolsos = @desembolsos.where("fecha >= ?", params[:desembolso][:desde]) unless params[:desembolso][:desde].blank?
		@desembolsos = @desembolsos.where("fecha <= ?", params[:desembolso][:hasta]) unless params[:desembolso][:hasta].blank?
		@desembolsos = @desembolsos.where("lower(proyectos.nombre) like ?",params[:desembolso][:proyecto]).joins(contrato: :proyecto) unless params[:desembolso][:proyecto].blank?
		@desembolsos = @desembolsos.where("lower(contratos.numero) like ?",params[:desembolso][:numero_contrato]).joins(:contrato) unless params[:desembolso][:numero_contrato].blank?

		unless params[:contrato_id].blank?
			render :index
		else
			render :list 
		end
	end
	def edit
		@desembolso = Desembolso.find(params[:id])
	end
	def destroy
		if @desembolso.destroy
			flash[:notice] = "El Desembolso ha sido eliminado satisfactoriamente."
			redirect_to proyecto_desembolsos_path(@proyecto)
		else
			flash.now[:error] = "Ocurrieron errores al eliminar."
      		render action: "index"
		end
	end
	def update
		if @desembolso.update(desembolso_params)
			flash[:notice] = "El Desembolso ha sido actualizado satisfactoriamente."
			redirect_to proyecto_desembolsos_path(@proyecto)
		else
			flash.now[:error] = "Ocurrieron errores al guardar."
      		render action: "edit"
		end
	end
	private
	def buscar_proyecto
		@proyecto = Proyecto.find(params[:proyecto_id]) if params[:proyecto_id]
	end
	def buscar_desembolso
		@desembolso = Desembolso.find(params[:id]) 
	end
	def buscar_fondos_financiamientos
		@fondos_financiamientos = FondoFinanciamiento.all
	end
	def buscar_estatus_transferencia
		@estatus_transferencia = EstatusTransferencia.all
	end
	def buscar_proyectos_financiamientos
		if @proyecto
			@proyectos_financiamientos = ProyectoFinanciamiento.where(:proyecto_id => @proyecto.id)
		else
			@proyectos_financiamientos = []
		end
	end
	def desembolso_params
    params.require(:desembolso).permit(:fecha, :monto, :valuacion, :observacion, :contrato_id, :fondo_financiamiento_id, :estatus_id, desembolsos_fuentes_attributes: [:desembolso_id, :proyecto_financiamiento_id, :moneda_id, :monto, :id, :_destroy])
  end
end

app/controllers/reportes/desembolsos_controller.rb
class Reportes::DesembolsosController < ApplicationController
	authorize_resource class: Reportes::DesembolsosController
	#Página principal del reporte. Alli es donde se visualizan los campos que filtran el reporte
	def index
	end

	def report		
		@desembolsos = Desembolso.order(:proyecto_id)
		@desembolsos = @desembolsos.where("estatus_id = ?", params[:search][:estatus_transferencia_id]) unless params[:search][:estatus_transferencia_id].blank?
		@desembolsos = @desembolsos.where("fecha >= ?", params[:search][:desde]) unless params[:search][:desde].blank?
		@desembolsos = @desembolsos.where("fecha <= ?", params[:search][:hasta]) unless params[:search][:hasta].blank?
		@desembolsos = @desembolsos.where("proyecto_id = ?", params[:search][:proyecto_id]) unless params[:search][:proyecto_id].blank?

		render "report", :formats => [:pdf]
	end
end

app/helpers/desembolsos_helper.rb
module DesembolsosHelper
end

app/helpers/reportes/desembolsos_helper.rb
module Reportes::DesembolsosHelper
end

app/views/desembolsos/_desembolso_fuente.html.haml
#desembolso_fuente
  = f.simple_fields_for :desembolsos_fuentes do |o|
    = render 'desembolso_fuente_fields', :f => o 
  .links
    = link_to_add_association(f, :desembolsos_fuentes,  { class: 'btn btn-icon glyphicons circle_plus btn-success' }){ content_tag('i') + ' Agregar Fuente de Financiamiento' }

app/views/desembolsos/_desembolso_fuente_fields.html.haml
.nested-fields.well  
  .row-fluid
    .span11
      .row-fluid
        = f.input :proyecto_financiamiento_id, collection: @proyectos_financiamientos, label_method: :nombre, value_method: :id, :label => 'Fuentes y Fondos de Financiamiento del Proyecto', prompt: "Fuentes y Fondos de Financiamiento del Proyecto", input_html: { class: 'span10' }
      .row-fluid
        = f.input :moneda_id, collection: Moneda.all, label_method: :nombre, value_method: :id, :label => 'Moneda', prompt: "Moneda", input_html: { class: 'span6' }
        = f.input :monto, input_html: { :id => 'monto' } 
      %br
    .span1
      %br
        = link_to_remove_association "Eliminar", f

app/views/desembolsos/_filtro.html.haml
= simple_form_for :desembolso, {url: search_proyecto_desembolsos_path, method: :get} do |f|
	.row-fluid
		.span4.first 
			= f.select :fondo_financiamiento_id, FondoFinanciamiento.all.map { |r| [r.nombre, r.id] }, {include_blank: "Fondo Financiamiento"}, {class: 'span12'}
		.span3
			= f.input :desde, label: false, placeholder: 'Desde', :as => :date_picker, input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
		.span3
			= f.input :hasta, label: false, placeholder: 'Hasta',:as => :date_picker, input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
	.row-fluid
		.span4
			= f.select :estatus_transferencia_id, EstatusTransferencia.all.map { |r| [r.nombre, r.id] }, {include_blank: "Estatus Transferencia"}, {class: 'span12'}
	.row-fluid
		.span12.first
			= button_tag(class: 'btn btn-icon btn-primary glyphicons search') do
				- content_tag(:i, '') + "Buscar"
			= link_to(proyecto_desembolsos_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
				- content_tag(:i, '') + "Cancelar"	
		

app/views/desembolsos/_form_fields.html.haml
%div.span10
	%div.row-fluid  
		.span2
			= f.input :fecha, required: true, :as => :date_picker
	%div.row-fluid  
		.span8
			= f.input :valuacion, required: true
	%div.row-fluid
		.span8
			= f.input :estatus_id, required: true, collection: @estatus_transferencia, label_method: :nombre, value_method: :id, :label => 'Estatus Transferencia', prompt: "Estatus Transferencia" 
	%div.row-fluid	
		.span12
			= f.input :observacion, as: :text, input_html: {maxlength: 255, row:2, class: 'span6'}
	%br
	%div.row-fluid	
		= render 'desembolso_fuente', :f => f  
      

app/views/desembolsos/edit.html.haml
%div.innerLR
  %h3 Editando Desembolso
  = render 'shared/descripcion_proyecto'
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link.active
          = link_to(proyecto_desembolsos_path, class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_desembolso_path, class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
    %div.widget-body
      %div.tab-content
        #list
          = simple_form_for @desembolso, {url: proyecto_desembolso_path, method: :put} do |f|
            
            = f.error_notification
            = flash_messages
            = render 'form_fields', :f => f
            %br
            = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
              - content_tag(:i, '') + "Guardar"
            = link_to(proyecto_desembolsos_path(@proyecto)  , class: 'btn btn-icon btn-default glyphicons circle_remove') do
              - content_tag(:i, '') + "Cancelar"  

app/views/desembolsos/index.html.haml
%ul.breadcrumb
  %li.false
    = link_to "Panel de control", rails_admin.dashboard_path, class: 'pjax'
    %span.divider="/"
  %li.active
    %a="Desembolsos"

%h3="Lista de Desembolsos"
= render 'shared/descripcion_proyecto'
%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link.active
          = link_to(proyecto_desembolsos_path, class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_desembolso_path, class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
        %li.icon.export_collection_link 
          = link_to('/admin/desembolso/export'){ content_tag(:i, '', class:"icon-share") + content_tag(:span, ' Exportar') }           
    %div.widget-body
      %div.tab-content
        %div.list
          = flash_messages
          %div.well
            .row-fluid.no-margin-bottom
              = render 'filtro'
          %table.table.table-condensed.table-striped
            %thead
              %tr
                %th="Número de Valuaión"  
                %th="Montos"
                %th="Fecha"
                %th="Estatus Transferencia"
                %th=""
            %tbody
              - @desembolsos.each do |d|
                %tr
                  %td= d.valuacion
                  %td= d.montos
                  %td= d.fecha
                  %td= d.estatus_transferencia.nombre
                  %td
                    = link_to(edit_proyecto_desembolso_path(@proyecto, d), class: 'pjax', title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }
                    = link_to(proyecto_desembolso_path(@proyecto, d), method: :delete, class: 'pjax', confirm: '¿Desea eliminar el Desembolso?', title: 'Eliminar'){ content_tag(:i, '', class:"icon-remove") }
      .clearfix.total-count= pluralize(@desembolsos.size, 'desembolso')

    

app/views/desembolsos/list.html.haml
%ul.breadcrumb
  %li.false
    = link_to "Panel de control", rails_admin.dashboard_path, class: 'pjax'
    %span.divider="/"
  %li.active
    %a="Desembolsos"

%h3="Lista de Desembolsos"

%div.innerLR
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.new_collection_link 
          = link_to(desembolsos_path, class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
    %div.widget-body
      %div.tab-content
        %div.list
          = flash_messages
          %div.well
            .row-fluid.no-margin-bottom
              = simple_form_for :desembolso, {url: search_desembolsos_path, method: :get} do |f|
                .row-fluid
                  .span4.first 
                    = f.select :fondo_financiamiento_id, FondoFinanciamiento.all.map { |r| [r.nombre, r.id] }, {include_blank: "Fondo Financiamiento"}, {class: 'span12'}  
                  .span3
                    = f.select :estatus_transferencia_id, EstatusTransferencia.all.map { |r| [r.nombre, r.id] }, {include_blank: "Estatus Transferencia"}, {class: 'span12'}
                  .span3
                    = f.input :numero_contrato, label: false, placeholder: 'Número de Contrato', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
                .row-fluid
                  .span4
                    = f.input :proyecto, label: false, placeholder: 'Proyecto', input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
                  .span3
                    = f.input :desde, label: false, placeholder: 'Desde', :as => :date_picker, input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
                  .span3
                    = f.input :hasta, label: false, placeholder: 'Hasta',:as => :date_picker, input_html: { class: 'span12'}, wrapper_html: {class: 'compact-horizontal'}
                  
                .row-fluid
                  .span12.first
                    = button_tag(class: 'btn btn-icon btn-primary glyphicons search') do
                      - content_tag(:i, '') + "Buscar"
                    = link_to(desembolsos_path , class: 'btn btn-icon btn-default glyphicons circle_remove') do
                      - content_tag(:i, '') + "Cancelar" 
          %table.table.table-condensed.table-striped
            %thead
              %tr
                %th="Proyecto"  
                %th="Nro. Valuacion"
                %th="Monto"
                %th="Fecha"
                %th="Estatus Transferencia"
                %th=""
            %tbody
              - @desembolsos.each do |d|
                %tr
                  %td= d.proyecto.nombre
                  %td= d.valuacion
                  %td= d.montos
                  %td= d.fecha
                  %td= d.estatus_transferencia.try(:nombre)
                  %td
                    = link_to(edit_proyecto_desembolso_path(d.proyecto, d), class: 'pjax', title: 'Editar'){ content_tag(:i, '', class:"icon-pencil") }
                    = link_to(proyecto_desembolso_path(d.proyecto, d), method: :delete, class: 'pjax', title: 'Eliminar', confirm: '¿Desea eliminar el Desembolso?'){ content_tag(:i, '', class:"icon-remove") }
      .clearfix.total-count= pluralize(@desembolsos.size, 'desembolso')

    

app/views/desembolsos/new.html.haml
%div.innerLR
  %h3 Agregar Nuevo Desembolso
  = render 'shared/descripcion_proyecto'
  %div.widget.widget-tabs
    %div.widget-head
      %ul.tabs
        %li.icon.index_collection_link.active
          = link_to(proyecto_desembolsos_path, class: 'pjax'){ content_tag(:i, '', class:"icon-th-list") + content_tag(:span, ' Listar') }
        %li.icon.new_collection_link 
          = link_to(new_proyecto_desembolso_path, class: 'pjax'){ content_tag(:i, '', class:"icon-plus") + content_tag(:span, ' Agregar Nuevo') }
    %div.widget-body
      %div.tab-content

        #list
          = simple_form_for @desembolso, {url: proyecto_desembolsos_path, method: :post} do |f| 
            
            = f.error_notification
            = flash_messages
            = render 'form_fields', :f => f
            %br
            = button_tag(class: 'btn btn-icon btn-primary glyphicons circle_ok') do
              - content_tag(:i, '') + "Guardar"
            = link_to(proyecto_desembolsos_path(@proyecto, @contrato)  , class: 'btn btn-icon btn-default glyphicons circle_remove') do
              - content_tag(:i, '') + "Cancelar"  

          